name: deno-test-action

on: [push, pull_request, workflow_dispatch]

jobs:
  linter_name:
    name: deno-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run all tests
        run: |
          deno task test
      - name: e2e test
        run: |
          deno task test:e2e
